//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class fabricante
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public fabricante()
    {
        this.modelo = new HashSet<modelo>();
    }

    public int id { get; set; }
    public string descricao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<modelo> modelo { get; set; }
}

public partial class imagens
{
    public int id { get; set; }
    public string arquivo { get; set; }
    public Nullable<bool> destaque { get; set; }
    public Nullable<int> veiculo_id { get; set; }

    public virtual veiculos veiculos { get; set; }
}

public partial class modelo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public modelo()
    {
        this.veiculos = new HashSet<veiculos>();
    }

    public int id { get; set; }
    public string descricao { get; set; }
    public Nullable<int> fabricante_id { get; set; }

    public virtual fabricante fabricante { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<veiculos> veiculos { get; set; }
}

public partial class tipos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipos()
    {
        this.veiculos = new HashSet<veiculos>();
    }

    public int id { get; set; }
    public string descricao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<veiculos> veiculos { get; set; }
}

public partial class veiculos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public veiculos()
    {
        this.imagens = new HashSet<imagens>();
    }

    public int id { get; set; }
    public string titulo { get; set; }
    public int modelo_id { get; set; }
    public string ano { get; set; }
    public string cor { get; set; }
    public Nullable<int> km { get; set; }
    public Nullable<decimal> preco { get; set; }
    public bool ativo { get; set; }
    public System.DateTime data_criacao { get; set; }
    public Nullable<bool> destaque { get; set; }
    public string descricao { get; set; }
    public Nullable<int> tipo_id { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<imagens> imagens { get; set; }
    public virtual modelo modelo { get; set; }
    public virtual tipos tipos { get; set; }
}
