//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class giulianoovendedorEntities : DbContext
{
    public giulianoovendedorEntities()
        : base("name=giulianoovendedorEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<fabricante> fabricante { get; set; }
    public virtual DbSet<imagens> imagens { get; set; }
    public virtual DbSet<modelo> modelo { get; set; }
    public virtual DbSet<tipos> tipos { get; set; }
    public virtual DbSet<veiculos> veiculos { get; set; }
}
